const data = {
    products: [
      {
        _id: '1',
        name: 'Tusker',
        category: 'Beer',
        image: '/images/p1.png',
        price: 120,
        brand: 'East African Breweries',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Pilsner Lager',
        category: 'Beer',
        image: '/images/p2.png',
        price: 100,
        brand: 'East African Breweries',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Tusker Malt',
        category: 'Beer',
        image: '/images/p3.png',
        price: 220,
        brand: 'East African Breweries',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'White Cap Lager',
        category: 'Beer',
        image: '/images/p4.png',
        price: 78,
        brand: 'East African Breweries',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Tusker Lite',
        category: 'Beer',
        image: '/images/p5.png',
        price: 65,
        brand: 'East African Breweries',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Summit Lager',
        category: 'Beer',
        image: '/images/p6.jfif',
        price: 139,
        brand: 'East African Breweries',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;